import = [ "~/.config/alacritty/github_dark_default.toml" ]


[font]
  normal.family = 'JetBrains Mono'
  normal.style = 'Regular'

  bold.family = "JetBrains Mono"
  bold.style = "Bold"

  italic.family = "JetBrains Mono"
  italic.style = "Italic"

  offset.x = 0
  offset.y = 0

  glyph_offset.x = 0
  glyph_offset.y = 0

[env]
  TERM = "xterm-256color"

